name: front-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code.
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache node module use
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Create env file
        run: |
          echo VITE_APP_FIREBASE_API_KEY=`${{ secrets.VITE_APP_FIREBASE_API_KEY }}` >> /.env
          echo VITE_APP_FIREBASE_AUTH_DOMAIN=`${{ secrets.VITE_APP_FIREBASE_AUTH_DOMAIN }}` >> /.env
          echo VITE_APP_FIREBASE_PROJECT_ID=`${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }}` >> /.env
          echo VITE_APP_FIREBASE_STORAGE_BUCKET=`${{ secrets.VITE_APP_FIREBASE_STORAGE_BUCKET }}` >> /.env
          echo VITE_APP_FIREBASE_MESSAGING_SENDER_ID=`${{ secrets.VITE_APP_FIREBASE_MESSAGING_SENDER_ID }}` >> /.env
          echo VITE_APP_FIREBASE_APP_ID=`${{ secrets.VITE_APP_FIREBASE_APP_ID }}` >> /.env
          echo VITE_APP_IMP_CODE=`${{ secrets.VITE_APP_IMP_CODE }}` >> /.env

      - name: build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./dist s3://$BUCKET_NAME

      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.DEV_AWS_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUD_FRONT_ID --paths /*
